apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandicoot-staging
  labels:
    ver: "2"
    app: bandicoot
    env: staging 
spec:
  selector:
    matchLabels:
      ver: "2"
      app: bandicoot
      env: staging     
  replicas: 1
  template:
    metadata:
      labels:
        ver: "2"
        app: bandicoot
        env: staging     
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:2
